### ISSUE TITLE
public IP error

### ISSUE THREAD

**Issue by sam13591980** [haythem/public-ip#9]
Hello,
I am using Nodejs and request module to call "https://api6.ipify.org/?format=json" link to get public address. I get error -101.
The following codes to get the public IP of my server (I changed some info for the IP that backed from error anyhow) and still an error :

```
    let request = require('request');
    let url="https://api6.ipify.org/?format=json";
    request.get({  
        url: url,
        json: true,
        headers: {'User-Agent': 'request'}
      }, (err, resGet, data) => {
        if (!err) {
         console.log(data.ip);
        }else{
          console.log(err);
        }
    });
```

Error:

```
Error: connect ENETUNREACH 2000:aaaa:bbbb:c::1:443 - Local (:::0)
0|main.min  |     at internalConnect (net.js:922:16)
0|main.min  |     at defaultTriggerAsyncIdScope (internal/async_hooks.js:429:12)
0|main.min  |     at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1062:9)
0|main.min  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8) {
0|main.min  |   errno: -101,
0|main.min  |   code: 'ENETUNREACH',
0|main.min  |   syscall: 'connect',
0|main.min  |   address: '2000:aaaa:bbbb:c::1',
0|main.min  |   port: 443
0|main.min  | }

```

**Comment by sam13591980** [comment]
I found the issue :
the link is changed to https://api64.ipify.org/?format=json

**Comment by haythem** [comment]
Hello @sam13591980,

This issue you're having is not related to this project.
